[theme]
primaryColor = "#2962FF"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
